### ISSUE TITLE
Full Stack JavaScript Courses to be completed

### ISSUE THREAD

**Issue by deniselookingout** [deniselookingout/treehouse#2]
## TODO

_Courses left to complete the Treehouse Full Stack JavaScript Track_
- [ ] JavaScript Basics
- [ ] Javascript Loops, Arrays and Objects
- [ ] jQuery Basics
- [ ] Using jQuery Plugins
- [ ] Interactive Web Pages with JavaScript
- [ ] AJAX Basics
- [ ] Understanding "this" in JavaScript
- [ ] Object-oriented JavaScript
- [ ] The Module Patter in JavaScript
- [ ] Node.js Basics
- [ ] Build a Simple Dynamic Site with Node.js
- [ ] npm Basics
- [ ] Using npm as a Task Runner
- [ ] Git Basics
- [ ] Express Basics
- [ ] Gulp Basics
- [ ] Angular Basics
- [ ] Mongo Basics
- [ ] Build a MEAN Application
- [ ] JavaScript Unit Testing

🎉
